BEGIN;
INSERT INTO django_content_type VALUES(1,'admin','logentry') ON CONFLICT (id) DO NOTHING;
INSERT INTO django_content_type VALUES(2,'auth','permission') ON CONFLICT (id) DO NOTHING;
INSERT INTO django_content_type VALUES(3,'auth','group') ON CONFLICT (id) DO NOTHING;
INSERT INTO django_content_type VALUES(4,'contenttypes','contenttype') ON CONFLICT (id) DO NOTHING;
INSERT INTO django_content_type VALUES(5,'sessions','session') ON CONFLICT (id) DO NOTHING;
INSERT INTO django_content_type VALUES(6,'talks','customuser') ON CONFLICT (id) DO NOTHING;
INSERT INTO django_content_type VALUES(7,'talks','ad') ON CONFLICT (id) DO NOTHING;
INSERT INTO django_content_type VALUES(8,'talks','category') ON CONFLICT (id) DO NOTHING;
INSERT INTO django_content_type VALUES(9,'talks','userprofile') ON CONFLICT (id) DO NOTHING;
INSERT INTO django_content_type VALUES(10,'talks','comment') ON CONFLICT (id) DO NOTHING;
INSERT INTO auth_permission VALUES(1,1,'add_logentry','Can add log entry') ON CONFLICT (id) DO NOTHING;
INSERT INTO auth_permission VALUES(2,1,'change_logentry','Can change log entry') ON CONFLICT (id) DO NOTHING;
INSERT INTO auth_permission VALUES(3,1,'delete_logentry','Can delete log entry') ON CONFLICT (id) DO NOTHING;
INSERT INTO auth_permission VALUES(4,1,'view_logentry','Can view log entry') ON CONFLICT (id) DO NOTHING;
INSERT INTO auth_permission VALUES(5,2,'add_permission','Can add permission') ON CONFLICT (id) DO NOTHING;
INSERT INTO auth_permission VALUES(6,2,'change_permission','Can change permission') ON CONFLICT (id) DO NOTHING;
INSERT INTO auth_permission VALUES(7,2,'delete_permission','Can delete permission') ON CONFLICT (id) DO NOTHING;
INSERT INTO auth_permission VALUES(8,2,'view_permission','Can view permission') ON CONFLICT (id) DO NOTHING;
INSERT INTO auth_permission VALUES(9,3,'add_group','Can add group') ON CONFLICT (id) DO NOTHING;
INSERT INTO auth_permission VALUES(10,3,'change_group','Can change group') ON CONFLICT (id) DO NOTHING;
INSERT INTO auth_permission VALUES(11,3,'delete_group','Can delete group') ON CONFLICT (id) DO NOTHING;
INSERT INTO auth_permission VALUES(12,3,'view_group','Can view group') ON CONFLICT (id) DO NOTHING;
INSERT INTO auth_permission VALUES(13,4,'add_contenttype','Can add content type') ON CONFLICT (id) DO NOTHING;
INSERT INTO auth_permission VALUES(14,4,'change_contenttype','Can change content type') ON CONFLICT (id) DO NOTHING;
INSERT INTO auth_permission VALUES(15,4,'delete_contenttype','Can delete content type') ON CONFLICT (id) DO NOTHING;
INSERT INTO auth_permission VALUES(16,4,'view_contenttype','Can view content type') ON CONFLICT (id) DO NOTHING;
INSERT INTO auth_permission VALUES(17,5,'add_session','Can add session') ON CONFLICT (id) DO NOTHING;
INSERT INTO auth_permission VALUES(18,5,'change_session','Can change session') ON CONFLICT (id) DO NOTHING;
INSERT INTO auth_permission VALUES(19,5,'delete_session','Can delete session') ON CONFLICT (id) DO NOTHING;
INSERT INTO auth_permission VALUES(20,5,'view_session','Can view session') ON CONFLICT (id) DO NOTHING;
INSERT INTO auth_permission VALUES(21,6,'add_customuser','Can add user') ON CONFLICT (id) DO NOTHING;
INSERT INTO auth_permission VALUES(22,6,'change_customuser','Can change user') ON CONFLICT (id) DO NOTHING;
INSERT INTO auth_permission VALUES(23,6,'delete_customuser','Can delete user') ON CONFLICT (id) DO NOTHING;
INSERT INTO auth_permission VALUES(24,6,'view_customuser','Can view user') ON CONFLICT (id) DO NOTHING;
INSERT INTO auth_permission VALUES(25,7,'add_ad','Can add ad') ON CONFLICT (id) DO NOTHING;
INSERT INTO auth_permission VALUES(26,7,'change_ad','Can change ad') ON CONFLICT (id) DO NOTHING;
INSERT INTO auth_permission VALUES(27,7,'delete_ad','Can delete ad') ON CONFLICT (id) DO NOTHING;
INSERT INTO auth_permission VALUES(28,7,'view_ad','Can view ad') ON CONFLICT (id) DO NOTHING;
INSERT INTO auth_permission VALUES(29,8,'add_category','Can add category') ON CONFLICT (id) DO NOTHING;
INSERT INTO auth_permission VALUES(30,8,'change_category','Can change category') ON CONFLICT (id) DO NOTHING;
INSERT INTO auth_permission VALUES(31,8,'delete_category','Can delete category') ON CONFLICT (id) DO NOTHING;
INSERT INTO auth_permission VALUES(32,8,'view_category','Can view category') ON CONFLICT (id) DO NOTHING;
INSERT INTO auth_permission VALUES(33,9,'add_userprofile','Can add user profile') ON CONFLICT (id) DO NOTHING;
INSERT INTO auth_permission VALUES(34,9,'change_userprofile','Can change user profile') ON CONFLICT (id) DO NOTHING;
INSERT INTO auth_permission VALUES(35,9,'delete_userprofile','Can delete user profile') ON CONFLICT (id) DO NOTHING;
INSERT INTO auth_permission VALUES(36,9,'view_userprofile','Can view user profile') ON CONFLICT (id) DO NOTHING;
INSERT INTO auth_permission VALUES(37,10,'add_comment','Can add comment') ON CONFLICT (id) DO NOTHING;
INSERT INTO auth_permission VALUES(38,10,'change_comment','Can change comment') ON CONFLICT (id) DO NOTHING;
INSERT INTO auth_permission VALUES(39,10,'delete_comment','Can delete comment') ON CONFLICT (id) DO NOTHING;
INSERT INTO auth_permission VALUES(40,10,'view_comment','Can view comment') ON CONFLICT (id) DO NOTHING;
INSERT INTO talks_category VALUES(1,'Official','Events and announcements from governmental or formal organizations.') ON CONFLICT (id) DO NOTHING;
INSERT INTO talks_category VALUES(2,'Events','Events, concerts, movies, shows, and other activities.') ON CONFLICT (id) DO NOTHING;
INSERT INTO talks_category VALUES(3,'Sports','Athletic events, competitions, and sports-related gatherings.') ON CONFLICT (id) DO NOTHING;
INSERT INTO talks_category VALUES(4,'Charity and Aid','Fundraisers, volunteer opportunities, and charitable activities.') ON CONFLICT (id) DO NOTHING;
INSERT INTO talks_category VALUES(5,'Commercial','Product launches, sales events, and other business-related activities.') ON CONFLICT (id) DO NOTHING;
INSERT INTO talks_category VALUES(6,'Wellness and Mindfulness','Yoga sessions, meditation classes, and workshops focusing on mental well-being.') ON CONFLICT (id) DO NOTHING;
INSERT INTO talks_category VALUES(7,'Art and Culture','Art exhibitions, cultural festivals, and museum events.') ON CONFLICT (id) DO NOTHING;
INSERT INTO talks_category VALUES(8,'Celebrations and Congrats','A space for sharing birthday wishes, achievements, and other celebratory messages.') ON CONFLICT (id) DO NOTHING;
INSERT INTO talks_category VALUES(9,'Miscellaneous','Items that don''t fit into other categories') ON CONFLICT (id) DO NOTHING;
INSERT INTO talks_userprofile VALUES(1,NULL,1) ON CONFLICT (id) DO NOTHING;
INSERT INTO talks_userprofile VALUES(3,NULL,3) ON CONFLICT (id) DO NOTHING;
INSERT INTO talks_userprofile VALUES(4,NULL,4) ON CONFLICT (id) DO NOTHING;
INSERT INTO talks_comment VALUES(1,'Super!','2023-10-09 19:56:11.601864',2,1) ON CONFLICT (id) DO NOTHING;
INSERT INTO talks_comment VALUES(36,'Happy birthday!!','2023-10-11 18:17:49.991119',8,3) ON CONFLICT (id) DO NOTHING;
INSERT INTO talks_comment VALUES(45,'Our balconies are our property. We do what we want with them. Freedom for our balconies! The mayor should resign!','2023-10-15 21:19:52.864273',10,3) ON CONFLICT (id) DO NOTHING;
INSERT INTO talks_comment VALUES(46,replace(replace('Could you please specify who exactly is the author of the painting? And has an expert evaluation been conducted?\r\nNataliya','\r',char(13)),'\n',char(10)),'2023-10-16 10:22:47.952672',7,1) ON CONFLICT (id) DO NOTHING;
INSERT INTO talks_ad_categories VALUES(2,2,3) ON CONFLICT (id) DO NOTHING;
INSERT INTO talks_ad_categories VALUES(5,4,2) ON CONFLICT (id) DO NOTHING;
INSERT INTO talks_ad_categories VALUES(6,4,7) ON CONFLICT (id) DO NOTHING;
INSERT INTO talks_ad_categories VALUES(8,6,5) ON CONFLICT (id) DO NOTHING;
INSERT INTO talks_ad_categories VALUES(9,7,5) ON CONFLICT (id) DO NOTHING;
INSERT INTO talks_ad_categories VALUES(10,7,7) ON CONFLICT (id) DO NOTHING;
INSERT INTO talks_ad_categories VALUES(11,8,8) ON CONFLICT (id) DO NOTHING;
INSERT INTO talks_ad_categories VALUES(12,9,9) ON CONFLICT (id) DO NOTHING;
INSERT INTO talks_ad_categories VALUES(13,10,1) ON CONFLICT (id) DO NOTHING;
INSERT INTO django_admin_log VALUES(1,'1','Official',1,'[{"added": {}}]',8,1,'2023-10-05 21:53:09.973054') ON CONFLICT (id) DO NOTHING;
INSERT INTO django_admin_log VALUES(2,'2','Events',1,'[{"added": {}}]',8,1,'2023-10-05 21:53:52.007185') ON CONFLICT (id) DO NOTHING;
INSERT INTO django_admin_log VALUES(3,'3','Sports',1,'[{"added": {}}]',8,1,'2023-10-05 21:54:22.985169') ON CONFLICT (id) DO NOTHING;
INSERT INTO django_admin_log VALUES(4,'4','Charity and Aid',1,'[{"added": {}}]',8,1,'2023-10-05 21:54:44.283190') ON CONFLICT (id) DO NOTHING;
INSERT INTO django_admin_log VALUES(5,'5','Commercial',1,'[{"added": {}}]',8,1,'2023-10-05 21:55:00.000189') ON CONFLICT (id) DO NOTHING;
INSERT INTO django_admin_log VALUES(6,'6','Wellness and Mindfulness',1,'[{"added": {}}]',8,1,'2023-10-05 21:55:17.510339') ON CONFLICT (id) DO NOTHING;
INSERT INTO django_admin_log VALUES(7,'7','Art and Culture',1,'[{"added": {}}]',8,1,'2023-10-05 21:55:37.895220') ON CONFLICT (id) DO NOTHING;
INSERT INTO django_admin_log VALUES(8,'8','Celebrations and Congrats',1,'[{"added": {}}]',8,1,'2023-10-05 21:55:56.738139') ON CONFLICT (id) DO NOTHING;
INSERT INTO django_admin_log VALUES(9,'9','Miscellaneous',1,'[{"added": {}}]',8,1,'2023-10-08 21:21:04.868274') ON CONFLICT (id) DO NOTHING;
INSERT INTO django_admin_log VALUES(10,'14','mama',3,'',6,1,'2023-10-19 13:07:56.791716') ON CONFLICT (id) DO NOTHING;
INSERT INTO django_session VALUES('dvg9vx0ta6f91dy7ya73p0vi65q38hh1','.eJxVjMsOwiAQRf-FtSEMBWbq0r3fQBgeUjU0Ke3K-O_apAvd3nPOfQkftrX6refFT0mcBYjT78YhPnLbQbqHdptlnNu6TCx3RR60y-uc8vNyuH8HNfT6rZ1FU0gPmCNrhFRKNk6xojSiIopUctBs3BgVIQwWSXFCsBEDlAIg3h_X-zeD:1qtYFu:UmX83Ox16TjpbDafVupr_Q0RI4Nnb5Q7FrncBN7B90g','2023-11-02 19:00:26.115424') ON CONFLICT (id) DO NOTHING;
INSERT INTO talks_ad VALUES(2,'Football match in Dortmund',replace(replace('Six countries. Five time zones. Three continents. Two different seasons. One World Cup.\r\n\r\nThe proposed plans for the 2030 tournament - to be held in South America, Africa and Europe - are difficult to imagine as a reality.\r\n\r\nIt will be the first time a World Cup has been played on more than one continent - 2002 was the only previous event with more than one host in neighbouring countries South Korea and Japan.\r\n\r\nThat will change when the USA, Mexico and Canada host in 2026 - but that will not match the scale of the 2030 World Cup.\r\n\r\nSpain, Portugal and Morocco have been named as co-hosts, yet the opening three matches will take place in Uruguay, Argentina and Paraguay to mark the World Cup''s centenary.\r\n\r\nBut how will it all work? And what are the likely implications for players and fans?','\r',char(13)),'\n',char(10)),'2023-10-07 06:27:57.576201','ads_images/football.jpg',3,0) ON CONFLICT (id) DO NOTHING;
INSERT INTO talks_ad VALUES(4,'Viennese Classics Night',replace(replace('Everyone is invited to a concert of Viennese classics on 10/25/2025 in the Grand Hall.\r\nThe program includes Mozart, Beethoven, Haydn.','\r',char(13)),'\n',char(10)),'2023-10-07 07:12:36.676177','ads_images/Viener.png',1,0) ON CONFLICT (id) DO NOTHING;
INSERT INTO talks_ad VALUES(6,'House in Alps','The beautiful house for sale.','2023-10-07 18:04:35.412055','ads_images/house1.jpg',3,0) ON CONFLICT (id) DO NOTHING;
INSERT INTO talks_ad VALUES(7,'Old master''s painting',replace(replace('Old master''s painting for sale. 2000 Euro\r\nPhone 0123456789','\r',char(13)),'\n',char(10)),'2023-10-08 21:14:24.754601','ads_images/Picture.jpg',4,0) ON CONFLICT (id) DO NOTHING;
INSERT INTO talks_ad VALUES(8,'Happy Birthday Lucia!!',replace(replace('Happy birthday and wish you all the best!\r\nMay all your dreams come true!\r\n\r\nYour neighbors','\r',char(13)),'\n',char(10)),'2023-10-08 21:19:18.561160','ads_images/Happy_birthday.jpg',1,0) ON CONFLICT (id) DO NOTHING;
INSERT INTO talks_ad VALUES(9,'The dog is missing',replace(replace('My beloved dog ran away while walking.\r\nIf you have seen her, please call 0123456789.\r\nMonica','\r',char(13)),'\n',char(10)),'2023-10-08 21:24:04.620962','ads_images/dog.jpg',3,0) ON CONFLICT (id) DO NOTHING;
INSERT INTO talks_ad VALUES(10,'Attention to all neighbors!','A new law banning UFO parking in the courtyards of apartment buildings and on balconies comes into force on June 1.','2023-10-08 21:28:27.178299','',1,0) ON CONFLICT (id) DO NOTHING;
INSERT INTO talks_customuser VALUES(1,'pbkdf2_sha256$600000$KsUQKE7xCXfXvpYsmx6Zvv$P8pkqnfsOHxMeTJ1AECZhvk1B/W/dUhyopGtQnlySfQ=','2023-10-19 19:00:26.108819',1,'Nataliya','','',1,1,'2023-10-05 21:51:27.413241','profile_pictures/a_beautiful_40-year-old_modern_strong-willed_powerful_well_9165b283-a19_vvNZEV5.png',0,'nataliyagergo@gmail.com') ON CONFLICT (id) DO NOTHING;
INSERT INTO talks_customuser VALUES(3,'pbkdf2_sha256$600000$F6NzUb6CccuakbMEV3kRiD$S6s2LWi4jxDNlimv4CPlHGw0XlehrSspzAyKxJB6o1E=','2023-10-16 20:05:58.961189',0,'test','','',0,1,'2023-10-05 23:03:58.136627','',0,'vernaal@mail.ru') ON CONFLICT (id) DO NOTHING;
INSERT INTO talks_customuser VALUES(4,'pbkdf2_sha256$600000$FkqScTiCmgz84eTqF8rzty$FNiTlViAesvqfjoNHd/XUOlwE4jZmlrmomZJ8kKcN4k=','2023-10-08 21:10:40.812979',0,'Lala','','',0,1,'2023-10-08 21:10:40.547295','profile_pictures/E8bw.jpg',0,'vernaal@gmail.com') ON CONFLICT (id) DO NOTHING;
COMMIT;
