# Generated by Django 4.2.4 on 2023-09-12 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0003_category_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='category',
        ),
        migrations.AddField(
            model_name='ad',
            name='categories',
            field=models.ManyToManyField(to='talks.category'),
        ),
    ]
